---
apiVersion: v1
kind: Namespace
metadata:
  name: image-clone-controller

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: image-clone-controller
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: serving-cert
  namespace: image-clone-controller
spec:
  dnsNames:
    - image-clone-controller.image-clone-controller.svc
    - image-clone-controller.image-clone-controller.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: webhook-server-cert
