---
apiVersion: v1
kind: Secret
metadata:
  name: backup-registry-creds
  namespace: image-clone-controller
type: Opaque
data:
  username: cGlvdHJrcGNiYWNrdXA=
  password: a3ViZXJtYXRpYw==
  registry: ZG9ja2VyLmlvL3Bpb3Rya3BjYmFja3Vw
---
apiVersion: v1
kind: Service
metadata:
  namespace: image-clone-controller
  name: image-clone-controller
  labels:
    app: image-clone-controller
spec:
  publishNotReadyAddresses: true
  ports:
    - port: 443
      targetPort: 9443
  selector:
    app: image-clone-controller

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: image-clone-controller
  name: image-clone-controller
  labels:
    app: image-clone-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-clone-controller
  template:
    metadata:
      name: image-clone-controller
      labels:
        app: image-clone-controller
    spec:
      containers:
        - name: mutator
          image: piotrkpc/image-clone-controller:v0.1.2
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 64Mi
          env:
            - name: BACKUP_REGISTRY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backup-registry-creds
                  key: username
            - name: BACKUP_REGISTRY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backup-registry-creds
                  key: password
            - name: BACKUP_REGISTRY
              valueFrom:
                secretKeyRef:
                  name: backup-registry-creds
                  key: registry
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: webhook-server-cert