apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: busybox-daemonset
spec:
  selector:
    matchLabels:
      app: busybox-daemonset
  template:
    metadata:
      labels:
        app: busybox-daemonset
    spec:
      containers:
        - name: busybox-daemonset
          image: busybox:latest
          command:
            - sleep
            - "36000"